: FIZZ?  3 MOD 0 = DUP IF ." FIZZ" THEN ;
: BUZZ?  5 MOD 0 = DUP IF ." BUZZ" THEN ;
: FIZZ-BUZZ?  DUP FIZZ? SWAP BUZZ? OR INVERT ;
: DO-FIZZ-BUZZ  25 1 DO CR i FIZZ-BUZZ? IF i . THEN LOOP ;
DO-FIZZ-BUZZ
cr bye

